<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Kylan Paige's Resume</title>
  <style>
    body {
      margin: 0;
      overflow: hidden;
    }
    iframe {
      width: 100%;
      height: 100vh;
      border: none;
    }
  </style>
</head>
<body>
  <iframe src="https://docs.google.com/gview?url=https://github.com/kylanpaige/resume/raw/main/Kylan-Paige-Business-Administration-Graduate.pdf&embedded=true"></iframe>
</body>
</html>
